[project]
name = "portfolio-optimization"
version = "1.0.0"
description = "Streamlit Portfolio Optimization App"
requires-python = ">=3.10"

dependencies = [
    "streamlit",
    "pandas",
    "numpy",
    "yfinance",
    "plotly",
    "scipy",
    "matplotlib>=3.10.8",
    "seaborn>=0.13.2",
    "datetime",
]

[dependency-groups]
dev = [
    "black",
    "ruff",
    "pytest"
]

