[project]
name = "kpi-recommender-system"
version = "1.0.0"
description = "Streamlit-based KPI recommender system"
requires-python = ">=3.11"

dependencies = [
    "streamlit",
    "pandas",
    "plotly",
    "scikit-learn",
]

[tool.uv]
dev-dependencies = [
    "black",
    "ruff",
    "pytest",
    "ipykernel",
    "jupyter"
]
